version: "3.6"

services:
    envoy:
        image: envoyproxy/envoy:v1.10.0
        command: envoy -c /etc/envoy/envoy.yaml
        volumes:
            - ./envoy:/etc/envoy
        ports:
            - 8080:8080
